[versions]
#kotlin2-lang = "2.2.0"
#kotlin2-logging = "7.0.7"
kotlin2-coroutines = "1.10.2"
kotlin2-io = "0.8.0"
kotlin2-arrow = "2.1.2"

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin2-lang" }
kotlin-logging = { module = "io.github.oshai:kotlin-logging-jvm", version.ref = "kotlin2-logging" }
kotlin-coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-bom", version.ref = "kotlin2-coroutines" }
kotlin-io = { module = "org.jetbrains.kotlinx:kotlinx-io-core", version.ref = "kotlin2-io" }
kotlin-arrow-core = { module = "io.arrow-kt:arrow-core", version.ref = "kotlin2-arrow" }
kotlin-arrow-fx = { module = "io.arrow-kt:arrow-fx-coroutines", version.ref = "kotlin2-arrow" }

logback = { module = "ch.qos.logback:logback-classic", version = "1.5.18" }

commons-lang3 = { module = "org.apache.commons:commons-lang3", version = "3.18.0" }
guava = { module = "com.google.guava:guava", version = "33.4.8-jre" }

commons-math4 = { module = "org.apache.commons:commons-math4-legacy", version = "4.0-beta1" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin2-lang" }
#mockito = { id = "com.bakdata.mockito", version = "1.10.0" }

[bundles]
kotlin-arrow = ["kotlin-arrow-core", "kotlin-arrow-fx"]
